Update password
vaticle/typedb-client-nodejs pull request #179
Opened 2021-06-21 19:19 UTC by lolski

**For the title of this PR:** please follow the grammatical rules of a usual publication title, without capitalisation (except for the first letter). Thus, the title should NOT CONTAIN CODE: no dots, no parentheses, no backticks, no brackets, etc. It needs to be distinctive (not detailed) and succinct (not lengthy). Details of this PR will go in the description. **For the description of this PR:** please replace every line in curly brackets ( { like this } ) with an appropriate description following the guidance. Finally, **please remove this paragraph**.

## What is the goal of this PR?

{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related GitHub issues. This section will be automatically compiled into the release notes, so please:
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new product behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.
  - Use the _Royal We_: _"We"_ made changes, not _"I"_ made changes. }

## What are the changes implemented in this PR?

{ Please explain what you implemented, why your changes are the best way to achieve the goal(s) above. Please describe every method, class and package, by explaining:
  - its responsibility, 
  - how it's expected to behave, and 
  - how it relates to the adjacent methods/classes/packages it interacts with. 

This would allow the reviewer to understand your intentions in the code much better. If you're adding new classes, make sure these explanations are also included in the class header comments. Last but not least, please reference the GitHub issues to be automatically closed, such like 'closes #number'. }

2021-06-23 10:31 UTC, flyingsilverfin requested changes

2021-06-23 10:31 UTC, flyingsilverfin commented on common/rpc/RequestBuilder.ts
> +                return new ClusterUserProto.Password.Req().setName(password);
eh? `setName()` takes the `password`? seems like a bug

2021-06-23 10:31 UTC, flyingsilverfin commented on test/behaviour/cucumber_test.sh
> +  ROOT_CA=`realpath ./typedb-cluster-all/"$DIRECTORY"/server/conf/encryption/rpc-root-ca.pem`
why did you rename it to `cluster-all` when it can be also used for `core`? (shown by the `== "Core"`) check above?

2021-06-23 10:31 UTC, flyingsilverfin commented on test/common/stop-cluster-servers.sh
> +rm -rf 1 2 3 typedb-cluster-all
nice lol

2021-06-23 10:58 UTC, lolski commented on common/rpc/RequestBuilder.ts
> +                return new ClusterUserProto.Password.Req().setName(password);
Oops! Fixed in https://github.com/vaticle/typedb-client-nodejs/pull/179/commits/3b3758144bbac89b6e892ea28e9a65b8e7c3f1d5

2021-06-23 10:58 UTC, lolski commented on test/behaviour/cucumber_test.sh
> +  ROOT_CA=`realpath ./typedb-cluster-all/"$DIRECTORY"/server/conf/encryption/rpc-root-ca.pem`
You're correct, it's been fixed in https://github.com/vaticle/typedb-client-nodejs/pull/179/commits/da2d735c22a342fc3b5cfceacc8dc739adc730a3

2021-06-24 12:36 UTC, flyingsilverfin approved these changes

2021-06-24 12:40 UTC, merged