Transaction timeout
vaticle/typedb-client-nodejs pull request #197
Opened 2021-12-21 22:00 UTC by flyingsilverfin

**For the title of this PR:** please follow the grammatical rules of a usual publication title, without capitalisation (except for the first letter). Thus, the title should NOT CONTAIN CODE: no dots, no parentheses, no backticks, no brackets, etc. It needs to be distinctive (not detailed) and succinct (not lengthy). Details of this PR will go in the description. **For the description of this PR:** please replace every line in curly brackets ( { like this } ) with an appropriate description following the guidance. Finally, **please remove this paragraph**.

## What is the goal of this PR?

{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related GitHub issues. This section will be automatically compiled into the release notes, so please:
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new product behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.
  - Use the _Royal We_: _"We"_ made changes, not _"I"_ made changes. }

## What are the changes implemented in this PR?

{ Please explain what you implemented, why your changes are the best way to achieve the goal(s) above. Please describe every method, class and package, by explaining:
  - its responsibility, 
  - how it's expected to behave, and 
  - how it relates to the adjacent methods/classes/packages it interacts with. 

This would allow the reviewer to understand your intentions in the code much better. If you're adding new classes, make sure these explanations are also included in the class header comments. Last but not least, please reference the GitHub issues to be automatically closed, such like 'closes #number'. }

2021-12-22 14:18 UTC, flyingsilverfin commented
TODO update grpc

2022-01-10 19:19 UTC, flyingsilverfin reviewed
Still want to see if I can reduce size of package.lock diff... or is it ok that's 14k lines change?? Manually updated yarn.lock because i didn't want a 10k differ there too :(

2022-01-10 19:19 UTC, flyingsilverfin commented on stream/ResponseCollector.ts
> +            this._queue.add(new Done());
major change: when we receive an error, we immediate put the `ResponseCollector` into a error state, and put `Done` message on the queue to unblock any waiting, which will return as an error above if there is an error set

2022-01-10 19:19 UTC, flyingsilverfin commented on stream/ResponseCollector.ts
> +            else throw new TypeDBClientError(ILLEGAL_STATE);
if it's a `Done`, and there is an error state, we throw the error. Otherwise we just say it's a closed transaction :)

2022-01-10 19:19 UTC, flyingsilverfin commented on stream/ResponseCollector.ts
> -            return this._error;
keeping an error inside the `Done` element is no longer necessary

2022-01-10 19:19 UTC, flyingsilverfin commented on test/behaviour/connection/ConnectionStepsBase.ts
> +};
new option setters for BDD

2022-01-10 19:19 UTC, flyingsilverfin commented on test/behaviour/connection/ConnectionStepsBase.ts
>          await db.delete();
made these generic methods to be re-used by `Core` and `Cluster` connection steps

2022-01-10 19:19 UTC, flyingsilverfin commented on test/behaviour/connection/ConnectionStepsCluster.ts
> +});
initialising a cluster scenario involves the normal `before()` and then setting various session/transaction options we always have on

2022-01-10 19:19 UTC, flyingsilverfin commented on test/behaviour/connection/ConnectionStepsCore.ts
> +});
same thing here

2022-01-10 19:19 UTC, flyingsilverfin commented on test/behaviour/connection/ConnectionStepsCluster.ts
> +After(async () => after());
for symmetry we also call the `after()` in the `ConnectionStepsBase.ts` class here

2022-01-10 19:19 UTC, flyingsilverfin commented on test/behaviour/connection/session/SessionSteps.ts
> +});
setter for connection options

2022-01-10 19:19 UTC, flyingsilverfin commented on test/behaviour/cucumber_test.sh
> +  ./typedb-distribution/"$DIRECTORY"/typedb server --storage.data typedb_test &
new test server argument format!

2022-01-11 10:45 UTC, flyingsilverfin commented on BUILD
> +    "//test/behaviour/util:UtilSteps.ts",
following other clients' we extract the `wait` steps into their own `UtilSteps` file

2022-01-11 13:43 UTC, alexjpwalker requested changes

2022-01-11 13:43 UTC, alexjpwalker commented on connection/TypeDBTransactionImpl.ts
> +import assert = require("assert");
We've never used `assert` before in Client NodeJS's **production** code.

Unlike in Java, there is no clean way to turn off assertions in NodeJS. (Methods typically used include **hot module replacement** - literally stripping the statements out of the source code before running it - and modifying the `assert` prototype to replace `assert` with a no-op function at runtime!)

I think we're better off replacing it with `throw new TypeDBClientError`. We've done this elsewhere (see `TypeDBClientImpl.session` which throws a Client NodeJS-only error if the session ID already exists).

2022-01-11 13:43 UTC, alexjpwalker commented on package.json
> +    "google-protobuf": "3.15.5",
Is this upgrade intentional?

2022-01-11 13:43 UTC, alexjpwalker commented on stream/ResponseCollector.ts
> +            else if (element.isDone() && this._error) throw new TypeDBClientError(TRANSACTION_CLOSED_WITH_ERRORS.message(this._error));
I remember this came up in conversation: did we agree to leave the error there even after reading it for the first time? (seems like the right thing to do, just confirming intent)

2022-01-11 13:43 UTC, alexjpwalker commented on test/behaviour/connection/ConnectionStepsCluster.ts
> +    before();
We're emulating inheritance here. The Cucumber structure doesn't allow for actual inheritance because it's based on top-level functions, not class functions.

So it might be clearer to call these methods `beforeBase` and `afterBase`. It makes it more obvious that they are only a partial implementation of `Before` - the equivalent of calling `super()` in Java (or JS).

2022-01-11 13:43 UTC, alexjpwalker commented on test/behaviour/util/BUILD
> +exports_files(["Util.ts", "UtilSteps.ts"])
Hmm, I wonder if it's weird having a `Util` and a `UtilSteps` in the same package, given that (almost) every other package in `behaviour` contains only one `.ts` file, namely `<packageName>Steps.ts`.

Might be ok!

2022-01-11 13:56 UTC, flyingsilverfin commented on test/behaviour/util/BUILD
> +exports_files(["Util.ts", "UtilSteps.ts"])
eh this is how it is in the other client's i'm keeping it!

2022-01-11 13:57 UTC, flyingsilverfin commented on stream/ResponseCollector.ts
> +            else if (element.isDone() && this._error) throw new TypeDBClientError(TRANSACTION_CLOSED_WITH_ERRORS.message(this._error));
Yep we did!

2022-01-11 13:57 UTC, flyingsilverfin commented on package.json
> +    "google-protobuf": "3.15.5",
Err noo will revert

2022-01-11 14:22 UTC, alexjpwalker approved these changes

2022-01-11 14:22 UTC, alexjpwalker commented on connection/TypeDBTransactionImpl.ts
> +import assert = require("assert");
```suggestion
```
And delete the now-unused import

2022-01-14 20:41 UTC, merged