Made datetime attribute insert and match time-zone invariant
vaticle/typedb-client-nodejs pull request #228
Opened 2023-06-27 14:27 UTC by shiladitya-mukherjee

Fixed the bug that datetime attributes when inserted through client-nodejs returned incorrectly with offset depending on the system timezone. We have also added set time-zone step implementation to help write Scenario tests in BDD. We have also fixed the parsing for Attributes and Values in scenarios which was previously broken for datetime attributes. 

## What is the goal of this PR?

{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related GitHub issues. This section will be automatically compiled into the release notes, so please:
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new product behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.
  - Use the _Royal We_: _"We"_ made changes, not _"I"_ made changes. }

## What are the changes implemented in this PR?

- Added "set time-zone is: {time_zone_label}" which sets environment timezone to time_zone_label.
- For correct parsing of datetime attributes, added function splitWithTail which splits a string only at the first `count` delimiters.
- Fixed datetime attribute parsing in both ConceptAPI and TypeQL.

2023-06-29 08:56 UTC, krishnangovindraj requested changes
Some cleanup needed

2023-06-29 08:56 UTC, krishnangovindraj commented on test/behaviour/typeql/TypeQLSteps.ts
> +}
We could try to parse the string with a regex so we don't need to introduce a new function.
It would be less code added overall.

2023-06-29 08:56 UTC, krishnangovindraj commented on test/behaviour/typeql/TypeQLSteps.ts
> +        console.log("value = ", s);
You forgot to clean up the `console.log`.

2023-06-29 08:56 UTC, krishnangovindraj commented on test/behaviour/typeql/TypeQLSteps.ts
> +        {
We tend to do have the brace on the same line.

2023-06-29 08:56 UTC, krishnangovindraj commented on test/behaviour/util/UtilSteps.ts
> +);
For consistency, We should do `});` on the same line.

2023-06-29 08:56 UTC, krishnangovindraj commented on yarn.lock
> +  integrity sha512-5zkh6040JaIwazELjhwMLUoHzcFXtTNes90YyMKA+6B0UrtBtMsS+aJJr+cRivw+neUd7uFT6sVvUyq7rQ6zOg==
Do you know why this changed?

2023-06-29 08:56 UTC, krishnangovindraj commented on test/behaviour/config/Parameters.ts
> +       return new Date(date.getTime() - userTimezoneOffset);
What is this meant to do? 
It looks like we're changing the parsed datetime to UTC explicitly, whereas the behaviour in other clients would be to try to treat it as timezone naive.

2023-06-29 17:27 UTC, krishnangovindraj requested changes

2023-06-29 17:27 UTC, krishnangovindraj commented on test/behaviour/typeql/TypeQLSteps.ts
> +        }
We shouldn't be doing any correction on the attribute being tested.
I think the original test was more correct, unless it does some fancy cross-timezone equality. We can add an equality check on their timezone info to overcome this.

2023-06-29 18:35 UTC, krishnangovindraj commented on test/behaviour/typeql/TypeQLSteps.ts
> +        }
As you correctly pointed out, this is just converting the parsed string to the right timestamp and comparing the times, without touching the attribute.
So this should be perfect.

2023-06-30 11:44 UTC, krishnangovindraj approved these changes
Looks good except for the newline in repositories.bzl

2023-06-30 11:44 UTC, krishnangovindraj commented on yarn.lock
> +  integrity sha512-5zkh6040JaIwazELjhwMLUoHzcFXtTNes90YyMKA+6B0UrtBtMsS+aJJr+cRivw+neUd7uFT6sVvUyq7rQ6zOg==
It's autogenerated and we keep it checked in.
So this should be here.

2023-07-03 17:20 UTC, flyingsilverfin approved these changes

2023-07-03 17:21 UTC, merged